// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type ActivitiesAnnualStatements struct {
	ActionDate                  string `json:"ActionDate"`
	AnnualStatementStatus       string `json:"AnnualStatementStatus"`
	AnnualStatementStatusRemark string `json:"AnnualStatementStatusRemark"`
	AssignedTo                  string `json:"AssignedTo"`
	AssignedToFullName          string `json:"AssignedToFullName"`
	Created                     string `json:"Created"`
	Creator                     string `json:"Creator"`
	CreatorFullName             string `json:"CreatorFullName"`
	Description                 string `json:"Description"`
	Division                    int    `json:"Division"`
	HID                         int    `json:"HID"`
	ID                          string `json:"ID"`
	Message                     string `json:"Message"`
	Modified                    string `json:"Modified"`
	Modifier                    string `json:"Modifier"`
	ModifierFullName            string `json:"ModifierFullName"`
	MyFirmUserEmail             string `json:"MyFirmUserEmail"`
	Status                      int    `json:"Status"`
	StatusDescription           string `json:"StatusDescription"`
	Type                        string `json:"Type"`
	Url                         string `json:"Url"`
}

type ActivitiesAnnualStatementsGetResponse struct {
}

type ActivitiesAnnualStatementsPostResponse struct {
}

type ActivitiesAnnualStatementsPutResponse struct {
}

type ActivitiesCommunicationNotes struct {
	Account             string `json:"Account"`
	AccountName         string `json:"AccountName"`
	Attachments         string `json:"Attachments"`
	Campaign            string `json:"Campaign"`
	CampaignDescription string `json:"CampaignDescription"`
	Contact             string `json:"Contact"`
	ContactFullName     string `json:"ContactFullName"`
	Created             string `json:"Created"`
	Creator             string `json:"Creator"`
	CreatorFullName     string `json:"CreatorFullName"`
	Date                string `json:"Date"`
	Division            int    `json:"Division"`
	Document            string `json:"Document"`
	DocumentSubject     string `json:"DocumentSubject"`
	HID                 int    `json:"HID"`
	ID                  string `json:"ID"`
	Modified            string `json:"Modified"`
	Modifier            string `json:"Modifier"`
	ModifierFullName    string `json:"ModifierFullName"`
	Notes               string `json:"Notes"`
	Opportunity         string `json:"Opportunity"`
	OpportunityName     string `json:"OpportunityName"`
	Status              int    `json:"Status"`
	StatusDescription   string `json:"StatusDescription"`
	Subject             string `json:"Subject"`
	User                string `json:"User"`
	UserFullName        string `json:"UserFullName"`
}

type ActivitiesCommunicationNotesGetResponse struct {
}

type ActivitiesCommunicationNotesPostResponse struct {
}

type ActivitiesComplaints struct {
	Account            string `json:"Account"`
	AccountName        string `json:"AccountName"`
	AssignedTo         string `json:"AssignedTo"`
	AssignedToFullName string `json:"AssignedToFullName"`
	Attachments        string `json:"Attachments"`
	Complaint          string `json:"Complaint"`
	Contact            string `json:"Contact"`
	ContactFullName    string `json:"ContactFullName"`
	Created            string `json:"Created"`
	Creator            string `json:"Creator"`
	CreatorFullName    string `json:"CreatorFullName"`
	Division           int    `json:"Division"`
	Document           string `json:"Document"`
	DocumentSubject    string `json:"DocumentSubject"`
	HID                int    `json:"HID"`
	ID                 string `json:"ID"`
	Modified           string `json:"Modified"`
	Modifier           string `json:"Modifier"`
	ModifierFullName   string `json:"ModifierFullName"`
	NextAction         string `json:"NextAction"`
	Notes              string `json:"Notes"`
	ReceiptDate        string `json:"ReceiptDate"`
	Status             int    `json:"Status"`
	StatusDescription  string `json:"StatusDescription"`
}

type ActivitiesComplaintsGetResponse struct {
}

type ActivitiesComplaintsPostResponse struct {
}

type ActivitiesEvents struct {
	Account             string `json:"Account"`
	AccountName         string `json:"AccountName"`
	Attachments         string `json:"Attachments"`
	Campaign            string `json:"Campaign"`
	CampaignDescription string `json:"CampaignDescription"`
	Contact             string `json:"Contact"`
	ContactFullName     string `json:"ContactFullName"`
	Created             string `json:"Created"`
	Creator             string `json:"Creator"`
	CreatorFullName     string `json:"CreatorFullName"`
	Description         string `json:"Description"`
	Division            int    `json:"Division"`
	Document            string `json:"Document"`
	DocumentSubject     string `json:"DocumentSubject"`
	EndDate             string `json:"EndDate"`
	HID                 int    `json:"HID"`
	ID                  string `json:"ID"`
	Modified            string `json:"Modified"`
	Modifier            string `json:"Modifier"`
	ModifierFullName    string `json:"ModifierFullName"`
	Notes               string `json:"Notes"`
	Opportunity         string `json:"Opportunity"`
	OpportunityName     string `json:"OpportunityName"`
	Project             string `json:"Project"`
	ProjectDescription  string `json:"ProjectDescription"`
	StartDate           string `json:"StartDate"`
	Status              int    `json:"Status"`
	StatusDescription   string `json:"StatusDescription"`
	User                string `json:"User"`
	UserFullName        string `json:"UserFullName"`
}

type ActivitiesEventsGetResponse struct {
}

type ActivitiesEventsPostResponse struct {
}

type ActivitiesFiscals struct {
	ActionDate         string `json:"ActionDate"`
	AssignedTo         string `json:"AssignedTo"`
	AssignedToFullName string `json:"AssignedToFullName"`
	Created            string `json:"Created"`
	Creator            string `json:"Creator"`
	CreatorFullName    string `json:"CreatorFullName"`
	Description        string `json:"Description"`
	Division           int    `json:"Division"`
	FiscalStatus       string `json:"FiscalStatus"`
	FiscalStatusRemark string `json:"FiscalStatusRemark"`
	HID                int    `json:"HID"`
	ID                 string `json:"ID"`
	Message            string `json:"Message"`
	Modified           string `json:"Modified"`
	Modifier           string `json:"Modifier"`
	ModifierFullName   string `json:"ModifierFullName"`
	MyFirmUserEmail    string `json:"MyFirmUserEmail"`
	Status             int    `json:"Status"`
	StatusDescription  string `json:"StatusDescription"`
	Type               string `json:"Type"`
	Url                string `json:"Url"`
}

type ActivitiesFiscalsGetResponse struct {
}

type ActivitiesFiscalsPostResponse struct {
}

type ActivitiesFiscalsPutResponse struct {
}

type ActivitiesServiceRequests struct {
	Account            string `json:"Account"`
	AccountName        string `json:"AccountName"`
	AssignedTo         string `json:"AssignedTo"`
	AssignedToFullName string `json:"AssignedToFullName"`
	Attachments        string `json:"Attachments"`
	Contact            string `json:"Contact"`
	ContactFullName    string `json:"ContactFullName"`
	Created            string `json:"Created"`
	Creator            string `json:"Creator"`
	CreatorFullName    string `json:"CreatorFullName"`
	Description        string `json:"Description"`
	Division           int    `json:"Division"`
	Document           string `json:"Document"`
	DocumentSubject    string `json:"DocumentSubject"`
	HID                int    `json:"HID"`
	ID                 string `json:"ID"`
	Modified           string `json:"Modified"`
	Modifier           string `json:"Modifier"`
	ModifierFullName   string `json:"ModifierFullName"`
	NextAction         string `json:"NextAction"`
	Notes              string `json:"Notes"`
	ReceiptDate        string `json:"ReceiptDate"`
	Status             int    `json:"Status"`
	StatusDescription  string `json:"StatusDescription"`
}

type ActivitiesServiceRequestsGetResponse struct {
}

type ActivitiesServiceRequestsPostResponse struct {
}

type ActivitiesTasks struct {
	Account             string `json:"Account"`
	AccountName         string `json:"AccountName"`
	ActionDate          string `json:"ActionDate"`
	Attachments         string `json:"Attachments"`
	Contact             string `json:"Contact"`
	ContactFullName     string `json:"ContactFullName"`
	Created             string `json:"Created"`
	Creator             string `json:"Creator"`
	CreatorFullName     string `json:"CreatorFullName"`
	CustomTaskType      string `json:"CustomTaskType"`
	Description         string `json:"Description"`
	Division            int    `json:"Division"`
	Document            string `json:"Document"`
	DocumentSubject     string `json:"DocumentSubject"`
	Employee            string `json:"Employee"`
	HID                 int    `json:"HID"`
	ID                  string `json:"ID"`
	Modified            string `json:"Modified"`
	Modifier            string `json:"Modifier"`
	ModifierFullName    string `json:"ModifierFullName"`
	Notes               string `json:"Notes"`
	Opportunity         string `json:"Opportunity"`
	OpportunityName     string `json:"OpportunityName"`
	Project             string `json:"Project"`
	ProjectDescription  string `json:"ProjectDescription"`
	Status              int    `json:"Status"`
	StatusDescription   string `json:"StatusDescription"`
	TaskType            int    `json:"TaskType"`
	TaskTypeDescription string `json:"TaskTypeDescription"`
	User                string `json:"User"`
	UserFullName        string `json:"UserFullName"`
}

type ActivitiesTasksGetResponse struct {
}

type ActivitiesTasksPostResponse struct {
}
