linters:
  enable:
    - errorlint
    - govet
    - ineffassign
    - staticcheck
    - unused
<<<<<<< HEAD
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
=======
>>>>>>> origin/main

formatters:
  enable:
    - gofmt
    - goimports
