// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newActivitiesFiscalsPutCmd(flags *rootFlags) *cobra.Command {
	var bodyActionDate string
	var bodyAssignedTo string
	var bodyAssignedToFullName string
	var bodyCreated string
	var bodyCreator string
	var bodyCreatorFullName string
	var bodyDescription string
	var bodyFiscalStatus string
	var bodyFiscalStatusRemark string
	var bodyHID int
	var bodyID string
	var bodyMessage string
	var bodyModified string
	var bodyModifier string
	var bodyModifierFullName string
	var bodyMyFirmUserEmail string
	var bodyStatus int
	var bodyStatusDescription string
	var bodyType string
	var bodyUrl string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "fiscals-put <division>",
		Short:       "The date indicating by when the action has to be taken; The user that the request is assigned to. Official docs:...",
		Example:     "  exact-online-activities-pp-cli activities fiscals-put 42",
		Annotations: map[string]string{"pp:endpoint": "activities.fiscals-put", "pp:method": "PUT", "pp:path": "/api/v1/{division}/activities/Fiscals"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/{division}/activities/Fiscals"
			path = replacePathParam(path, "division", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyActionDate != "" {
					body["ActionDate"] = bodyActionDate
				}
				if bodyAssignedTo != "" {
					body["AssignedTo"] = bodyAssignedTo
				}
				if bodyAssignedToFullName != "" {
					body["AssignedToFullName"] = bodyAssignedToFullName
				}
				if bodyCreated != "" {
					body["Created"] = bodyCreated
				}
				if bodyCreator != "" {
					body["Creator"] = bodyCreator
				}
				if bodyCreatorFullName != "" {
					body["CreatorFullName"] = bodyCreatorFullName
				}
				if bodyDescription != "" {
					body["Description"] = bodyDescription
				}
				if bodyFiscalStatus != "" {
					body["FiscalStatus"] = bodyFiscalStatus
				}
				if bodyFiscalStatusRemark != "" {
					body["FiscalStatusRemark"] = bodyFiscalStatusRemark
				}
				if bodyHID != 0 {
					body["HID"] = bodyHID
				}
				if bodyID != "" {
					body["ID"] = bodyID
				}
				if bodyMessage != "" {
					body["Message"] = bodyMessage
				}
				if bodyModified != "" {
					body["Modified"] = bodyModified
				}
				if bodyModifier != "" {
					body["Modifier"] = bodyModifier
				}
				if bodyModifierFullName != "" {
					body["ModifierFullName"] = bodyModifierFullName
				}
				if bodyMyFirmUserEmail != "" {
					body["MyFirmUserEmail"] = bodyMyFirmUserEmail
				}
				if bodyStatus != 0 {
					body["Status"] = bodyStatus
				}
				if bodyStatusDescription != "" {
					body["StatusDescription"] = bodyStatusDescription
				}
				if bodyType != "" {
					body["Type"] = bodyType
				}
				if bodyUrl != "" {
					body["Url"] = bodyUrl
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "activities",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyActionDate, "action-date", "", "The date indicating by when the action has to be taken")
	cmd.Flags().StringVar(&bodyAssignedTo, "assigned-to", "", "The user that the request is assigned to")
	cmd.Flags().StringVar(&bodyAssignedToFullName, "assigned-to-full-name", "", "The user name")
	cmd.Flags().StringVar(&bodyCreated, "created", "", "Creation date")
	cmd.Flags().StringVar(&bodyCreator, "creator", "", "User ID of the creator")
	cmd.Flags().StringVar(&bodyCreatorFullName, "creator-full-name", "", "Name of the creator")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description")
	cmd.Flags().StringVar(&bodyFiscalStatus, "fiscal-status", "", "The status of the Fiscal request")
	cmd.Flags().StringVar(&bodyFiscalStatusRemark, "fiscal-status-remark", "", "The remark of the Fiscal request status")
	cmd.Flags().IntVar(&bodyHID, "hid", 0, "The human readable key")
	cmd.Flags().StringVar(&bodyID, "id", "", "The Primary key")
	cmd.Flags().StringVar(&bodyMessage, "message", "", "The message content of the Fiscal request")
	cmd.Flags().StringVar(&bodyModified, "modified", "", "Last modified date")
	cmd.Flags().StringVar(&bodyModifier, "modifier", "", "User ID of the last modifier")
	cmd.Flags().StringVar(&bodyModifierFullName, "modifier-full-name", "", "Name of the last modifier")
	cmd.Flags().StringVar(&bodyMyFirmUserEmail, "my-firm-user-email", "", "The email of MyFirm user")
	cmd.Flags().IntVar(&bodyStatus, "status", 0, "Status: 0 = Void, 5 = Rejected, 10 = Draft, 20 = Open, 30 = Approved, 40 = Realized, 50 = Processed")
	cmd.Flags().StringVar(&bodyStatusDescription, "status-description", "", "The description of the status")
	cmd.Flags().StringVar(&bodyType, "type", "", "The message content of the Fiscal request")
	cmd.Flags().StringVar(&bodyUrl, "url", "", "The URL back to Fiscal")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
