// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newActivitiesCommunicationNotesPostCmd(flags *rootFlags) *cobra.Command {
	var bodyAccount string
	var bodyAccountName string
	var bodyAttachments string
	var bodyCampaign string
	var bodyCampaignDescription string
	var bodyContact string
	var bodyContactFullName string
	var bodyCreated string
	var bodyCreator string
	var bodyCreatorFullName string
	var bodyDate string
	var bodyDocument string
	var bodyDocumentSubject string
	var bodyHID int
	var bodyID string
	var bodyModified string
	var bodyModifier string
	var bodyModifierFullName string
	var bodyNotes string
	var bodyOpportunity string
	var bodyOpportunityName string
	var bodyStatus int
	var bodyStatusDescription string
	var bodySubject string
	var bodyUser string
	var bodyUserFullName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "communication-notes-post <division>",
		Short:       "The account that is related to the communication note; The name of the account. Official docs:...",
		Example:     "  exact-online-activities-pp-cli activities communication-notes-post 42",
		Annotations: map[string]string{"pp:endpoint": "activities.communication-notes-post", "pp:method": "POST", "pp:path": "/api/v1/{division}/activities/CommunicationNotes"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/{division}/activities/CommunicationNotes"
			path = replacePathParam(path, "division", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAccount != "" {
					body["Account"] = bodyAccount
				}
				if bodyAccountName != "" {
					body["AccountName"] = bodyAccountName
				}
				if bodyAttachments != "" {
					body["Attachments"] = bodyAttachments
				}
				if bodyCampaign != "" {
					body["Campaign"] = bodyCampaign
				}
				if bodyCampaignDescription != "" {
					body["CampaignDescription"] = bodyCampaignDescription
				}
				if bodyContact != "" {
					body["Contact"] = bodyContact
				}
				if bodyContactFullName != "" {
					body["ContactFullName"] = bodyContactFullName
				}
				if bodyCreated != "" {
					body["Created"] = bodyCreated
				}
				if bodyCreator != "" {
					body["Creator"] = bodyCreator
				}
				if bodyCreatorFullName != "" {
					body["CreatorFullName"] = bodyCreatorFullName
				}
				if bodyDate != "" {
					body["Date"] = bodyDate
				}
				if bodyDocument != "" {
					body["Document"] = bodyDocument
				}
				if bodyDocumentSubject != "" {
					body["DocumentSubject"] = bodyDocumentSubject
				}
				if bodyHID != 0 {
					body["HID"] = bodyHID
				}
				if bodyID != "" {
					body["ID"] = bodyID
				}
				if bodyModified != "" {
					body["Modified"] = bodyModified
				}
				if bodyModifier != "" {
					body["Modifier"] = bodyModifier
				}
				if bodyModifierFullName != "" {
					body["ModifierFullName"] = bodyModifierFullName
				}
				if bodyNotes != "" {
					body["Notes"] = bodyNotes
				}
				if bodyOpportunity != "" {
					body["Opportunity"] = bodyOpportunity
				}
				if bodyOpportunityName != "" {
					body["OpportunityName"] = bodyOpportunityName
				}
				if bodyStatus != 0 {
					body["Status"] = bodyStatus
				}
				if bodyStatusDescription != "" {
					body["StatusDescription"] = bodyStatusDescription
				}
				if bodySubject != "" {
					body["Subject"] = bodySubject
				}
				if bodyUser != "" {
					body["User"] = bodyUser
				}
				if bodyUserFullName != "" {
					body["UserFullName"] = bodyUserFullName
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "activities",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAccount, "account", "", "The account that is related to the communication note")
	cmd.Flags().StringVar(&bodyAccountName, "account-name", "", "The name of the account")
	cmd.Flags().StringVar(&bodyAttachments, "attachments", "", "Attachments linked to the communication note")
	cmd.Flags().StringVar(&bodyCampaign, "campaign", "", "The campaign linked to the communication note")
	cmd.Flags().StringVar(&bodyCampaignDescription, "campaign-description", "", "Description of the campaign")
	cmd.Flags().StringVar(&bodyContact, "contact", "", "The contact person that is related to the communication note")
	cmd.Flags().StringVar(&bodyContactFullName, "contact-full-name", "", "The name of the contact person")
	cmd.Flags().StringVar(&bodyCreated, "created", "", "Creation date")
	cmd.Flags().StringVar(&bodyCreator, "creator", "", "User ID of the creator")
	cmd.Flags().StringVar(&bodyCreatorFullName, "creator-full-name", "", "Name of the creator")
	cmd.Flags().StringVar(&bodyDate, "date", "", "The date")
	cmd.Flags().StringVar(&bodyDocument, "document", "", "The document that is linked to the communication note")
	cmd.Flags().StringVar(&bodyDocumentSubject, "document-subject", "", "The subject of the document")
	cmd.Flags().IntVar(&bodyHID, "hid", 0, "The human readable key")
	cmd.Flags().StringVar(&bodyID, "id", "", "The Primary key")
	cmd.Flags().StringVar(&bodyModified, "modified", "", "Last modified date")
	cmd.Flags().StringVar(&bodyModifier, "modifier", "", "User ID of the last modifier")
	cmd.Flags().StringVar(&bodyModifierFullName, "modifier-full-name", "", "Name of the last modifier")
	cmd.Flags().StringVar(&bodyNotes, "notes", "", "The notes of the communication note")
	cmd.Flags().StringVar(&bodyOpportunity, "opportunity", "", "The opportunity linked to the communication note")
	cmd.Flags().StringVar(&bodyOpportunityName, "opportunity-name", "", "The name of the opportunity")
	cmd.Flags().IntVar(&bodyStatus, "status", 0, "Status: 0 = Void, 5 = Rejected, 10 = Draft, 20 = Open, 30 = Approved, 40 = Realized, 50 = Processed")
	cmd.Flags().StringVar(&bodyStatusDescription, "status-description", "", "The description of the status")
	cmd.Flags().StringVar(&bodySubject, "subject", "", "A short description of the communication note")
	cmd.Flags().StringVar(&bodyUser, "user", "", "The user that the communication note is assigned to")
	cmd.Flags().StringVar(&bodyUserFullName, "user-full-name", "", "The user name")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
