<<<<<<< HEAD
// Copyright 2026 Hermes CLI Agent and contributors. Licensed under Apache-2.0. See LICENSE.
=======
// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
>>>>>>> origin/main
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newActivitiesAnnualStatementsGetCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "annual-statements-get <division>",
		Aliases:     []string{"get"},
<<<<<<< HEAD
		Short:       "The date indicating by when the action has to be taken; The status of the Annual Statement request.",
=======
		Short:       "The date indicating by when the action has to be taken; The status of the Annual Statement request. Official docs:...",
>>>>>>> origin/main
		Example:     "  exact-online-activities-pp-cli activities annual-statements-get 42",
		Annotations: map[string]string{"pp:endpoint": "activities.annual-statements-get", "pp:method": "GET", "pp:path": "/api/v1/{division}/activities/AnnualStatements", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
<<<<<<< HEAD
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <division>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <division>"))
			}
			path := "/api/v1/{division}/activities/AnnualStatements"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("division is required\nUsage: %s <%s>", cmd.CommandPath(), "division"))
			}
			path = replacePathParam(path, "division", args[0])
=======
				return cmd.Help()
			}
>>>>>>> origin/main
			c, err := flags.newClient()
			if err != nil {
				return err
			}
<<<<<<< HEAD
			params := map[string]string{}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "live", "activities", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
=======

			path := "/api/v1/{division}/activities/AnnualStatements"
			path = replacePathParam(path, "division", args[0])
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "activities", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
>>>>>>> origin/main
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
<<<<<<< HEAD
					filtered = compactFields(filtered, nil)
=======
					filtered = compactFields(filtered)
>>>>>>> origin/main
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
<<<<<<< HEAD
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
=======
>>>>>>> origin/main
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
<<<<<<< HEAD
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
=======
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
>>>>>>> origin/main
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
<<<<<<< HEAD
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
=======
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
>>>>>>> origin/main
		},
	}

	return cmd
}
