// Copyright 2026 Hermes CLI Agent and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newActivitiesFiscalsPutCmd(flags *rootFlags) *cobra.Command {
	var bodyActionDate string
	var bodyAssignedTo string
	var bodyAssignedToFullName string
	var bodyCreated string
	var bodyCreator string
	var bodyCreatorFullName string
	var bodyDescription string
	var bodyDivision2 int
	var bodyFiscalStatus string
	var bodyFiscalStatusRemark string
	var bodyHID int
	var bodyID string
	var bodyMessage string
	var bodyModified string
	var bodyModifier string
	var bodyModifierFullName string
	var bodyMyFirmUserEmail string
	var bodyStatus int
	var bodyStatusDescription string
	var bodyType string
	var bodyUrl string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "fiscals-put <division>",
		Short:       "The date indicating by when the action has to be taken; The user that the request is assigned to.",
		Example:     "  exact-online-activities-pp-cli activities fiscals-put 42",
		Annotations: map[string]string{"pp:endpoint": "activities.fiscals-put", "pp:method": "PUT", "pp:path": "/api/v1/{division}/activities/Fiscals"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <division>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <division>"))
			}
			if !stdinBody {
			}
			path := "/api/v1/{division}/activities/Fiscals"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("division is required\nUsage: %s <%s>", cmd.CommandPath(), "division"))
			}
			path = replacePathParam(path, "division", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("action-date") || bodyActionDate != "" {
					bodyMap["ActionDate"] = bodyActionDate
				}
				if cmd.Flags().Changed("assigned-to") || bodyAssignedTo != "" {
					bodyMap["AssignedTo"] = bodyAssignedTo
				}
				if cmd.Flags().Changed("assigned-to-full-name") || bodyAssignedToFullName != "" {
					bodyMap["AssignedToFullName"] = bodyAssignedToFullName
				}
				if cmd.Flags().Changed("created") || bodyCreated != "" {
					bodyMap["Created"] = bodyCreated
				}
				if cmd.Flags().Changed("creator") || bodyCreator != "" {
					bodyMap["Creator"] = bodyCreator
				}
				if cmd.Flags().Changed("creator-full-name") || bodyCreatorFullName != "" {
					bodyMap["CreatorFullName"] = bodyCreatorFullName
				}
				if cmd.Flags().Changed("description") || bodyDescription != "" {
					bodyMap["Description"] = bodyDescription
				}
				if cmd.Flags().Changed("division-2") || bodyDivision2 != 0 {
					bodyMap["Division"] = bodyDivision2
				}
				if cmd.Flags().Changed("fiscal-status") || bodyFiscalStatus != "" {
					bodyMap["FiscalStatus"] = bodyFiscalStatus
				}
				if cmd.Flags().Changed("fiscal-status-remark") || bodyFiscalStatusRemark != "" {
					bodyMap["FiscalStatusRemark"] = bodyFiscalStatusRemark
				}
				if cmd.Flags().Changed("hid") || bodyHID != 0 {
					bodyMap["HID"] = bodyHID
				}
				if cmd.Flags().Changed("id") || bodyID != "" {
					bodyMap["ID"] = bodyID
				}
				if cmd.Flags().Changed("message") || bodyMessage != "" {
					bodyMap["Message"] = bodyMessage
				}
				if cmd.Flags().Changed("modified") || bodyModified != "" {
					bodyMap["Modified"] = bodyModified
				}
				if cmd.Flags().Changed("modifier") || bodyModifier != "" {
					bodyMap["Modifier"] = bodyModifier
				}
				if cmd.Flags().Changed("modifier-full-name") || bodyModifierFullName != "" {
					bodyMap["ModifierFullName"] = bodyModifierFullName
				}
				if cmd.Flags().Changed("my-firm-user-email") || bodyMyFirmUserEmail != "" {
					bodyMap["MyFirmUserEmail"] = bodyMyFirmUserEmail
				}
				if cmd.Flags().Changed("status") || bodyStatus != 0 {
					bodyMap["Status"] = bodyStatus
				}
				if cmd.Flags().Changed("status-description") || bodyStatusDescription != "" {
					bodyMap["StatusDescription"] = bodyStatusDescription
				}
				if cmd.Flags().Changed("type") || bodyType != "" {
					bodyMap["Type"] = bodyType
				}
				if cmd.Flags().Changed("url") || bodyUrl != "" {
					bodyMap["Url"] = bodyUrl
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "activities", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "activities", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "activities",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyActionDate, "action-date", "", "The date indicating by when the action has to be taken")
	cmd.Flags().StringVar(&bodyAssignedTo, "assigned-to", "", "The user that the request is assigned to")
	cmd.Flags().StringVar(&bodyAssignedToFullName, "assigned-to-full-name", "", "The user name")
	cmd.Flags().StringVar(&bodyCreated, "created", "", "Creation date")
	cmd.Flags().StringVar(&bodyCreator, "creator", "", "User ID of the creator")
	cmd.Flags().StringVar(&bodyCreatorFullName, "creator-full-name", "", "Name of the creator")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description")
	cmd.Flags().IntVar(&bodyDivision2, "division-2", 0, "The division")
	cmd.Flags().StringVar(&bodyFiscalStatus, "fiscal-status", "", "The status of the Fiscal request")
	cmd.Flags().StringVar(&bodyFiscalStatusRemark, "fiscal-status-remark", "", "The remark of the Fiscal request status")
	cmd.Flags().IntVar(&bodyHID, "hid", 0, "The human readable key")
	cmd.Flags().StringVar(&bodyID, "id", "", "The Primary key")
	cmd.Flags().StringVar(&bodyMessage, "message", "", "The message content of the Fiscal request")
	cmd.Flags().StringVar(&bodyModified, "modified", "", "Last modified date")
	cmd.Flags().StringVar(&bodyModifier, "modifier", "", "User ID of the last modifier")
	cmd.Flags().StringVar(&bodyModifierFullName, "modifier-full-name", "", "Name of the last modifier")
	cmd.Flags().StringVar(&bodyMyFirmUserEmail, "my-firm-user-email", "", "The email of MyFirm user")
	cmd.Flags().IntVar(&bodyStatus, "status", 0, "Status: 0 = Void, 5 = Rejected, 10 = Draft, 20 = Open, 30 = Approved, 40 = Realized, 50 = Processed")
	cmd.Flags().StringVar(&bodyStatusDescription, "status-description", "", "The description of the status")
	cmd.Flags().StringVar(&bodyType, "type", "", "The message content of the Fiscal request")
	cmd.Flags().StringVar(&bodyUrl, "url", "", "The URL back to Fiscal")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
