<<<<<<< HEAD
// Copyright 2026 Hermes CLI Agent and contributors. Licensed under Apache-2.0. See LICENSE.
=======
// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
>>>>>>> origin/main
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newActivitiesTasksPostCmd(flags *rootFlags) *cobra.Command {
	var bodyAccount string
	var bodyAccountName string
	var bodyActionDate string
	var bodyAttachments string
	var bodyContact string
	var bodyContactFullName string
	var bodyCreated string
	var bodyCreator string
	var bodyCreatorFullName string
	var bodyCustomTaskType string
	var bodyDescription string
<<<<<<< HEAD
	var bodyDivision2 int
=======
>>>>>>> origin/main
	var bodyDocument string
	var bodyDocumentSubject string
	var bodyEmployee string
	var bodyHID int
	var bodyID string
	var bodyModified string
	var bodyModifier string
	var bodyModifierFullName string
	var bodyNotes string
	var bodyOpportunity string
	var bodyOpportunityName string
	var bodyProject string
	var bodyProjectDescription string
	var bodyStatus int
	var bodyStatusDescription string
	var bodyTaskType int
	var bodyTaskTypeDescription string
	var bodyUser string
	var bodyUserFullName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "tasks-post <division>",
<<<<<<< HEAD
		Short:       "The account that is related to the task; The name of the account. Official docs: https://start.exactonline.",
=======
		Short:       "The account that is related to the task; The name of the account. Official docs:...",
>>>>>>> origin/main
		Example:     "  exact-online-activities-pp-cli activities tasks-post 42",
		Annotations: map[string]string{"pp:endpoint": "activities.tasks-post", "pp:method": "POST", "pp:path": "/api/v1/{division}/activities/Tasks"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
<<<<<<< HEAD
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <division>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <division>"))
			}
			if !stdinBody {
			}
			path := "/api/v1/{division}/activities/Tasks"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("division is required\nUsage: %s <%s>", cmd.CommandPath(), "division"))
			}
			path = replacePathParam(path, "division", args[0])
=======
				return cmd.Help()
			}
			if !stdinBody {
			}
>>>>>>> origin/main
			c, err := flags.newClient()
			if err != nil {
				return err
			}
<<<<<<< HEAD
			params := map[string]string{}
			var body any
=======

			path := "/api/v1/{division}/activities/Tasks"
			path = replacePathParam(path, "division", args[0])
			var body map[string]any
>>>>>>> origin/main
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
<<<<<<< HEAD
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("account") || bodyAccount != "" {
					bodyMap["Account"] = bodyAccount
				}
				if cmd.Flags().Changed("account-name") || bodyAccountName != "" {
					bodyMap["AccountName"] = bodyAccountName
				}
				if cmd.Flags().Changed("action-date") || bodyActionDate != "" {
					bodyMap["ActionDate"] = bodyActionDate
				}
				if cmd.Flags().Changed("attachments") || bodyAttachments != "" {
					bodyMap["Attachments"] = bodyAttachments
				}
				if cmd.Flags().Changed("contact") || bodyContact != "" {
					bodyMap["Contact"] = bodyContact
				}
				if cmd.Flags().Changed("contact-full-name") || bodyContactFullName != "" {
					bodyMap["ContactFullName"] = bodyContactFullName
				}
				if cmd.Flags().Changed("created") || bodyCreated != "" {
					bodyMap["Created"] = bodyCreated
				}
				if cmd.Flags().Changed("creator") || bodyCreator != "" {
					bodyMap["Creator"] = bodyCreator
				}
				if cmd.Flags().Changed("creator-full-name") || bodyCreatorFullName != "" {
					bodyMap["CreatorFullName"] = bodyCreatorFullName
				}
				if cmd.Flags().Changed("custom-task-type") || bodyCustomTaskType != "" {
					bodyMap["CustomTaskType"] = bodyCustomTaskType
				}
				if cmd.Flags().Changed("description") || bodyDescription != "" {
					bodyMap["Description"] = bodyDescription
				}
				if cmd.Flags().Changed("division-2") || bodyDivision2 != 0 {
					bodyMap["Division"] = bodyDivision2
				}
				if cmd.Flags().Changed("document") || bodyDocument != "" {
					bodyMap["Document"] = bodyDocument
				}
				if cmd.Flags().Changed("document-subject") || bodyDocumentSubject != "" {
					bodyMap["DocumentSubject"] = bodyDocumentSubject
				}
				if cmd.Flags().Changed("employee") || bodyEmployee != "" {
					bodyMap["Employee"] = bodyEmployee
				}
				if cmd.Flags().Changed("hid") || bodyHID != 0 {
					bodyMap["HID"] = bodyHID
				}
				if cmd.Flags().Changed("id") || bodyID != "" {
					bodyMap["ID"] = bodyID
				}
				if cmd.Flags().Changed("modified") || bodyModified != "" {
					bodyMap["Modified"] = bodyModified
				}
				if cmd.Flags().Changed("modifier") || bodyModifier != "" {
					bodyMap["Modifier"] = bodyModifier
				}
				if cmd.Flags().Changed("modifier-full-name") || bodyModifierFullName != "" {
					bodyMap["ModifierFullName"] = bodyModifierFullName
				}
				if cmd.Flags().Changed("notes") || bodyNotes != "" {
					bodyMap["Notes"] = bodyNotes
				}
				if cmd.Flags().Changed("opportunity") || bodyOpportunity != "" {
					bodyMap["Opportunity"] = bodyOpportunity
				}
				if cmd.Flags().Changed("opportunity-name") || bodyOpportunityName != "" {
					bodyMap["OpportunityName"] = bodyOpportunityName
				}
				if cmd.Flags().Changed("project") || bodyProject != "" {
					bodyMap["Project"] = bodyProject
				}
				if cmd.Flags().Changed("project-description") || bodyProjectDescription != "" {
					bodyMap["ProjectDescription"] = bodyProjectDescription
				}
				if cmd.Flags().Changed("status") || bodyStatus != 0 {
					bodyMap["Status"] = bodyStatus
				}
				if cmd.Flags().Changed("status-description") || bodyStatusDescription != "" {
					bodyMap["StatusDescription"] = bodyStatusDescription
				}
				if cmd.Flags().Changed("task-type") || bodyTaskType != 0 {
					bodyMap["TaskType"] = bodyTaskType
				}
				if cmd.Flags().Changed("task-type-description") || bodyTaskTypeDescription != "" {
					bodyMap["TaskTypeDescription"] = bodyTaskTypeDescription
				}
				if cmd.Flags().Changed("user") || bodyUser != "" {
					bodyMap["User"] = bodyUser
				}
				if cmd.Flags().Changed("user-full-name") || bodyUserFullName != "" {
					bodyMap["UserFullName"] = bodyUserFullName
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "activities", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "activities", data, "")
=======
				body = map[string]any{}
				if bodyAccount != "" {
					body["Account"] = bodyAccount
				}
				if bodyAccountName != "" {
					body["AccountName"] = bodyAccountName
				}
				if bodyActionDate != "" {
					body["ActionDate"] = bodyActionDate
				}
				if bodyAttachments != "" {
					body["Attachments"] = bodyAttachments
				}
				if bodyContact != "" {
					body["Contact"] = bodyContact
				}
				if bodyContactFullName != "" {
					body["ContactFullName"] = bodyContactFullName
				}
				if bodyCreated != "" {
					body["Created"] = bodyCreated
				}
				if bodyCreator != "" {
					body["Creator"] = bodyCreator
				}
				if bodyCreatorFullName != "" {
					body["CreatorFullName"] = bodyCreatorFullName
				}
				if bodyCustomTaskType != "" {
					body["CustomTaskType"] = bodyCustomTaskType
				}
				if bodyDescription != "" {
					body["Description"] = bodyDescription
				}
				if bodyDocument != "" {
					body["Document"] = bodyDocument
				}
				if bodyDocumentSubject != "" {
					body["DocumentSubject"] = bodyDocumentSubject
				}
				if bodyEmployee != "" {
					body["Employee"] = bodyEmployee
				}
				if bodyHID != 0 {
					body["HID"] = bodyHID
				}
				if bodyID != "" {
					body["ID"] = bodyID
				}
				if bodyModified != "" {
					body["Modified"] = bodyModified
				}
				if bodyModifier != "" {
					body["Modifier"] = bodyModifier
				}
				if bodyModifierFullName != "" {
					body["ModifierFullName"] = bodyModifierFullName
				}
				if bodyNotes != "" {
					body["Notes"] = bodyNotes
				}
				if bodyOpportunity != "" {
					body["Opportunity"] = bodyOpportunity
				}
				if bodyOpportunityName != "" {
					body["OpportunityName"] = bodyOpportunityName
				}
				if bodyProject != "" {
					body["Project"] = bodyProject
				}
				if bodyProjectDescription != "" {
					body["ProjectDescription"] = bodyProjectDescription
				}
				if bodyStatus != 0 {
					body["Status"] = bodyStatus
				}
				if bodyStatusDescription != "" {
					body["StatusDescription"] = bodyStatusDescription
				}
				if bodyTaskType != 0 {
					body["TaskType"] = bodyTaskType
				}
				if bodyTaskTypeDescription != "" {
					body["TaskTypeDescription"] = bodyTaskTypeDescription
				}
				if bodyUser != "" {
					body["User"] = bodyUser
				}
				if bodyUserFullName != "" {
					body["UserFullName"] = bodyUserFullName
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
>>>>>>> origin/main
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
<<<<<<< HEAD
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
						}
=======
>>>>>>> origin/main
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
<<<<<<< HEAD
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
							}
=======
>>>>>>> origin/main
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
<<<<<<< HEAD
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "activities",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
=======
					return nil
				}
>>>>>>> origin/main
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
<<<<<<< HEAD
					filtered = compactFields(filtered, nil)
=======
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "activities",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
>>>>>>> origin/main
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
<<<<<<< HEAD
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
=======
						envelope["data"] = parsed
>>>>>>> origin/main
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
<<<<<<< HEAD
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "activities", partialFailure.Message))
			}
			return nil
=======
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
>>>>>>> origin/main
		},
	}
	cmd.Flags().StringVar(&bodyAccount, "account", "", "The account that is related to the task")
	cmd.Flags().StringVar(&bodyAccountName, "account-name", "", "The name of the account")
	cmd.Flags().StringVar(&bodyActionDate, "action-date", "", "The end date by which the task has to be realized")
	cmd.Flags().StringVar(&bodyAttachments, "attachments", "", "Attachments linked to the task")
	cmd.Flags().StringVar(&bodyContact, "contact", "", "The contact person that is related to the task")
	cmd.Flags().StringVar(&bodyContactFullName, "contact-full-name", "", "The name of the contact person")
	cmd.Flags().StringVar(&bodyCreated, "created", "", "Creation date")
	cmd.Flags().StringVar(&bodyCreator, "creator", "", "User ID of the creator")
	cmd.Flags().StringVar(&bodyCreatorFullName, "creator-full-name", "", "Name of the creator")
<<<<<<< HEAD
	cmd.Flags().StringVar(&bodyCustomTaskType, "custom-task-type", "", "Custom type of the task. If both TaskType and CustomTaskType are specified then TaskType is preferred.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description of the task")
	cmd.Flags().IntVar(&bodyDivision2, "division-2", 0, "The division of the task")
	cmd.Flags().StringVar(&bodyDocument, "document", "", "The document that is linked to the task")
	cmd.Flags().StringVar(&bodyDocumentSubject, "document-subject", "", "The subject of the document")
	cmd.Flags().StringVar(&bodyEmployee, "employee", "", "The employee that is linked to the task.")
=======
	cmd.Flags().StringVar(&bodyCustomTaskType, "custom-task-type", "", "Custom type of the task. If both TaskType and CustomTaskType are specified then TaskType is preferred. This value is...")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description of the task")
	cmd.Flags().StringVar(&bodyDocument, "document", "", "The document that is linked to the task")
	cmd.Flags().StringVar(&bodyDocumentSubject, "document-subject", "", "The subject of the document")
	cmd.Flags().StringVar(&bodyEmployee, "employee", "", "The employee that is linked to the task. Note : For POST/PUT: This field value is only used when the 'Employees'...")
>>>>>>> origin/main
	cmd.Flags().IntVar(&bodyHID, "hid", 0, "The human readable key")
	cmd.Flags().StringVar(&bodyID, "id", "", "The Primary key")
	cmd.Flags().StringVar(&bodyModified, "modified", "", "Last modified date")
	cmd.Flags().StringVar(&bodyModifier, "modifier", "", "User ID of the last modifier")
	cmd.Flags().StringVar(&bodyModifierFullName, "modifier-full-name", "", "Name of the last modifier")
	cmd.Flags().StringVar(&bodyNotes, "notes", "", "The notes of the task")
	cmd.Flags().StringVar(&bodyOpportunity, "opportunity", "", "The opportunity linked to the task")
	cmd.Flags().StringVar(&bodyOpportunityName, "opportunity-name", "", "The name of the opportunity")
	cmd.Flags().StringVar(&bodyProject, "project", "", "The project linked to the task")
	cmd.Flags().StringVar(&bodyProjectDescription, "project-description", "", "The description of the project")
	cmd.Flags().IntVar(&bodyStatus, "status", 0, "Status: 0 = Void, 5 = Rejected, 10 = Draft, 20 = Open, 30 = Approved, 40 = Realized, 50 = Processed")
	cmd.Flags().StringVar(&bodyStatusDescription, "status-description", "", "The description of the status")
<<<<<<< HEAD
	cmd.Flags().IntVar(&bodyTaskType, "task-type", 0, "The type of the task. This value is write-only.")
=======
	cmd.Flags().IntVar(&bodyTaskType, "task-type", 0, "The type of the task. This value is write-only.0 = Other (default), 1 = Call, 2 = Request for information, 3 =...")
>>>>>>> origin/main
	cmd.Flags().StringVar(&bodyTaskTypeDescription, "task-type-description", "", "The description of the type of the task")
	cmd.Flags().StringVar(&bodyUser, "user", "", "The user that has to realize the task")
	cmd.Flags().StringVar(&bodyUserFullName, "user-full-name", "", "The user name")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
