// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newActivitiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "activities",
		Short: "Manage activities",
	}

	cmd.AddCommand(newActivitiesAnnualStatementsGetCmd(flags))
	cmd.AddCommand(newActivitiesAnnualStatementsPostCmd(flags))
	cmd.AddCommand(newActivitiesAnnualStatementsPutCmd(flags))
	cmd.AddCommand(newActivitiesCommunicationNotesGetCmd(flags))
	cmd.AddCommand(newActivitiesCommunicationNotesPostCmd(flags))
	cmd.AddCommand(newActivitiesComplaintsGetCmd(flags))
	cmd.AddCommand(newActivitiesComplaintsPostCmd(flags))
	cmd.AddCommand(newActivitiesEventsGetCmd(flags))
	cmd.AddCommand(newActivitiesEventsPostCmd(flags))
	cmd.AddCommand(newActivitiesFiscalsGetCmd(flags))
	cmd.AddCommand(newActivitiesFiscalsPostCmd(flags))
	cmd.AddCommand(newActivitiesFiscalsPutCmd(flags))
	cmd.AddCommand(newActivitiesServiceRequestsGetCmd(flags))
	cmd.AddCommand(newActivitiesServiceRequestsPostCmd(flags))
	cmd.AddCommand(newActivitiesTasksGetCmd(flags))
	cmd.AddCommand(newActivitiesTasksPostCmd(flags))
	cmd.AddCommand(newActivitiesResourcesCmd(flags))
	cmd.AddCommand(newActivitiesDocsCmd(flags))
	cmd.AddCommand(newActivitiesOverviewCmd(flags))
	cmd.AddCommand(newActivitiesOpenItemsCmd(flags))
	cmd.AddCommand(newActivitiesByAccountCmd(flags))
	return cmd
}
