<<<<<<< HEAD
// Copyright 2026 Hermes CLI Agent and contributors. Licensed under Apache-2.0. See LICENSE.
=======
// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
>>>>>>> origin/main
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
<<<<<<< HEAD
	"os"
=======
	"time"
>>>>>>> origin/main

	"exact-online-activities-pp-cli/internal/store"
	"github.com/spf13/cobra"
)

func newWorkflowCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
<<<<<<< HEAD
		Use:         "workflow",
		Short:       "Compound workflows that combine multiple API operations",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}
=======
		Use:   "workflow",
		Short: "Compound workflows that combine multiple API operations",
	}
	cmd.AddCommand(newWorkflowArchiveCmd(flags))
>>>>>>> origin/main
	cmd.AddCommand(newWorkflowStatusCmd(flags))

	return cmd
}
<<<<<<< HEAD
=======
func newWorkflowArchiveCmd(flags *rootFlags) *cobra.Command {
	var dbPath string
	var full bool

	cmd := &cobra.Command{
		Use:   "archive",
		Short: "Sync all resources to local store for offline access and search",
		Long: `Archive fetches all syncable resources from the API and stores them in a
local SQLite database. Supports incremental sync (only new data since last run)
and full resync. After archiving, use 'search' for instant full-text search.`,
		Example: `  # Archive all resources
  exact-online-activities-pp-cli workflow archive

  # Full re-archive (ignore previous sync state)
  exact-online-activities-pp-cli workflow archive --full`,
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true

			if dbPath == "" {
				dbPath = defaultDBPath("exact-online-activities-pp-cli")
			}
			s, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening store: %w", err)
			}
			defer s.Close()

			resources := []string{}
			totalSynced := 0

			// --full clears the cursor here because syncResource reads
			// existingCursor unconditionally; its full param only gates the
			// since filter, not cursor reset. Mirrors newSyncCmd's pattern.
			if full {
				for _, resource := range resources {
					_ = s.SaveSyncState(resource, "", 0)
				}
			}

			for _, resource := range resources {
				res := syncResource(c, s, resource, "", full, 100, false, nil)
				if res.Err != nil {
					fmt.Fprintf(cmd.ErrOrStderr(), "  %s: error: %v\n", resource, res.Err)
					continue
				}
				if res.Warn != nil {
					fmt.Fprintf(cmd.ErrOrStderr(), "  %s: warning: %v\n", resource, res.Warn)
					continue
				}
				totalSynced += res.Count
				fmt.Fprintf(cmd.ErrOrStderr(), "  %s: %d synced\n", resource, res.Count)
			}

			if flags.asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(map[string]any{
					"resources_synced": len(resources),
					"total_items":      totalSynced,
					"store_path":       dbPath,
					"timestamp":        time.Now().UTC().Format(time.RFC3339),
				})
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Archived %d items across %d resources to %s\n", totalSynced, len(resources), dbPath)
			return nil
		},
	}

	cmd.Flags().StringVar(&dbPath, "db", "", "Database path (default: ~/.local/share/exact-online-activities-pp-cli/data.db)")
	cmd.Flags().BoolVar(&full, "full", false, "Full re-archive (ignore previous sync state)")

	return cmd
}
>>>>>>> origin/main

func newWorkflowStatusCmd(flags *rootFlags) *cobra.Command {
	var dbPath string

	cmd := &cobra.Command{
		Use:         "status",
		Short:       "Show local archive status and sync state for all resources",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Example: `  # Show archive status
  exact-online-activities-pp-cli workflow status

  # Show status as JSON
  exact-online-activities-pp-cli workflow status --json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if dbPath == "" {
				dbPath = defaultDBPath("exact-online-activities-pp-cli")
			}
<<<<<<< HEAD

			status := map[string]int{}
			if _, err := os.Stat(dbPath); err == nil {
				s, err := store.OpenReadOnlyContext(cmd.Context(), dbPath)
				if err != nil {
					return fmt.Errorf("opening store read-only: %w", err)
				}
				defer s.Close()

				schemaVersion, err := s.SchemaVersion()
				if err != nil {
					return fmt.Errorf("checking store schema read-only: %w", err)
				}
				if schemaVersion < store.StoreSchemaVersion {

					return fmt.Errorf("local store schema version %d requires migration to %d; this read-only command cannot migrate it; run the command that writes this store", schemaVersion, store.StoreSchemaVersion)

				}
				if schemaVersion > store.StoreSchemaVersion {
					return fmt.Errorf("local store schema version %d is newer than supported version %d; upgrade the CLI binary", schemaVersion, store.StoreSchemaVersion)
				}

				status, err = s.Status()
				if err != nil {
					return err
				}
			} else if !os.IsNotExist(err) {
				return fmt.Errorf("checking store path: %w", err)
=======
			s, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening store: %w", err)
			}
			defer s.Close()

			status, err := s.Status()
			if err != nil {
				return err
>>>>>>> origin/main
			}

			if flags.asJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(status)
			}

			if len(status) == 0 {
<<<<<<< HEAD
				fmt.Fprintln(cmd.OutOrStdout(), "No archived data. Add a site-specific sync command to populate the store.")
=======
				fmt.Fprintln(cmd.OutOrStdout(), "No archived data. Run 'workflow archive' to sync.")
>>>>>>> origin/main
				return nil
			}

			fmt.Fprintln(cmd.OutOrStdout(), "Archive Status:")
			total := 0
			for resource, count := range status {
				fmt.Fprintf(cmd.OutOrStdout(), "  %-30s %d items\n", resource, count)
				total += count
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\n  Total: %d items\n", total)
			fmt.Fprintf(cmd.OutOrStdout(), "  Store: %s\n", dbPath)
			return nil
		},
	}

<<<<<<< HEAD
	cmd.Flags().StringVar(&dbPath, "db", "", "SQLite database file path (default: resolved data directory data.db)")
=======
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path")
>>>>>>> origin/main

	return cmd
}

// defaultDBPath is defined in helpers.go
