<<<<<<< HEAD
// Copyright 2026 Hermes CLI Agent and contributors. Licensed under Apache-2.0. See LICENSE.
=======
// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
>>>>>>> origin/main
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
<<<<<<< HEAD
=======
	"fmt"
>>>>>>> origin/main
	"os"

	"exact-online-activities-pp-cli/internal/cli"
)

func main() {
	if err := cli.Execute(); err != nil {
<<<<<<< HEAD
=======
		fmt.Fprintln(os.Stderr, err.Error())
>>>>>>> origin/main
		os.Exit(cli.ExitCode(err))
	}
}
