<<<<<<< HEAD
// Copyright 2026 Hermes CLI Agent and contributors. Licensed under Apache-2.0. See LICENSE.
=======
// Copyright 2026 pimmetjeoss. Licensed under Apache-2.0. See LICENSE.
>>>>>>> origin/main
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"os"
	"os/exec"
	"path/filepath"
<<<<<<< HEAD
	"runtime"
=======
>>>>>>> origin/main
)

// SiblingCLIPath resolves the companion CLI via sibling-of-executable,
// EXACT_ONLINE_ACTIVITIES_CLI_PATH env var, then PATH.
func SiblingCLIPath() (string, error) {
<<<<<<< HEAD
	if exe, err := os.Executable(); err == nil {
		for _, candidate := range siblingCLICandidates(runtime.GOOS, exe) {
			if _, err := os.Stat(candidate); err == nil {
				return candidate, nil
			}
=======
	const cliName = "exact-online-activities-pp-cli"
	if exe, err := os.Executable(); err == nil {
		candidate := filepath.Join(filepath.Dir(exe), cliName)
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
>>>>>>> origin/main
		}
	}
	if v := os.Getenv("EXACT_ONLINE_ACTIVITIES_CLI_PATH"); v != "" {
		return v, nil
	}
<<<<<<< HEAD
	return exec.LookPath(cliExecutableName(runtime.GOOS))
}

func siblingCLICandidates(goos, exePath string) []string {
	dir := filepath.Dir(exePath)
	name := "exact-online-activities-pp-cli"
	if goos == "windows" {
		return []string{filepath.Join(dir, name+".exe"), filepath.Join(dir, name)}
	}
	return []string{filepath.Join(dir, name)}
}

func cliExecutableName(goos string) string {
	name := "exact-online-activities-pp-cli"
	if goos == "windows" {
		return name + ".exe"
	}
	return name
=======
	return exec.LookPath(cliName)
>>>>>>> origin/main
}
